### PR TITLE
Use split out python-openidc-client

### PR DESCRIPTION
**Pull request by puiterwijk**
Signed-off-by: Patrick Uiterwijk <puiterwijk@redhat.com>

### CODE REVIEW

**Comment by puiterwijk** [comment]
Upstream is at https://github.com/puiterwijk/python-openidc-client and this has been packaged for Fedora.

**Comment by pypingou** [comment]
The copyright year should be updated in that file.
We need to list this new dependency somewhere

Otherwise 👍 for the change itself.

Was python-openidc-client also packaged for all the epel branches?

**Comment by puiterwijk** [comment]
Looks like it's not yet in EPEL. I'll ask the packager to do so.

**Comment by pypingou** [comment]
Cool, 👍 for me

**Pull request merged**
