### PR TITLE
Python 3 compat fixes

### PR DESCRIPTION
**Pull request by scop**

### CODE REVIEW

**Comment by pypingou** [comment]
Even better :+1: for me

**Comment by scop** [comment]
Added a bunch of other sixifications and py3 related changes

**Comment by ralphbean** [comment]
Have you tried running the tests with ``tox``?  Did they pass?

**Comment by scop** [comment]
Yes, they do pass when run on my F23 box. I'm not sure why though, because looking at tox.ini it needs some love now that six 1.3 is no longer supported. Maybe that stuff concerns only the networked test stuff which I'm unable to test because connections to http://209.132.184.188 (from tests/functional/test_openidbaseclient.py) time out for me at the moment.

**Comment by ralphbean** [comment]
OK, I think we really can drop six-1.3 now that six-1.9.0 is in rhel7-base.

**Comment by ralphbean** [comment]
Thanks again @scop!

**Pull request merged**
