### PR TITLE
Actually check the server version when tickling.

### PR DESCRIPTION
**Pull request by ralphbean**
This is more explicit and will be sure to get around some of the
redirects we've been putting in place.

### CODE REVIEW

**Comment by laxathom** [comment]
:+1: on the check
Although, are we planning to maintain both version?

**Comment by ralphbean** [comment]
Not really, but we need it for the switchover so we can push this out, it lands on clients, and *then* we switch the server.

**Comment by ralphbean** [comment]
Thanks Xavier!

**Comment by lmacken** [comment]
:+1:

**Pull request merged**
