### PR TITLE
basestring is not in Python 3

### PR DESCRIPTION
**Pull request by rodrigc**

### CODE REVIEW

**Comment by abadger** [comment]
This will break python 2 so it's not a good change.

Using six.string_types might be okay if we do not need to support byte
strings on python 3.

We probably shouldn't touch the tg files as those can't be used with python
3 any way (turbogears1 isn't porting to python 3)

**Comment by rodrigc** [comment]
OK

**Comment by ralphbean** [comment]
:+1: here!  Thanks @rodrigc and @abadger!

**Comment by puiterwijk** [comment]
Hum. python-fedora-flask does not depend on python-six per the spec, and this PR didn't add that.

**Comment by rodrigc** [comment]
six was already in setup.py's install_requires :

https://github.com/fedora-infra/python-fedora/blob/develop/setup.py#L23

**Pull request merged**
