### PR TITLE
fixes of issue #288

### PR DESCRIPTION
**Pull request by trishnaguha**

### CODE REVIEW

**Comment by pypingou** [comment]
Which issue #288 is it? I don't see an issue #288 in this repo

**Comment by trishnaguha** [comment]
@pypingou 
https://github.com/fedora-infra/bodhi/issues/288

**Comment by pypingou** [comment]
Ok thanks and I am :+1: with the changes but will let @ralphbean or @lmacken do the merging

**Comment by trishnaguha** [comment]
Thanks @pypingou :)

**Comment by pypingou** [comment]
One question, I have tried to find you in the Fedora Account System (FAS: https://admin.fedoraproject.org/accounts ) but couldn't. Do you have an account there?
If so, did you sign the FPCA https://fedoraproject.org/wiki/Legal:Fedora_Project_Contributor_Agreement ?

If you do not wish to sign it, could you just make clear by replying here that your contribution is made under the same license than this project (ie: LGPLv2+) by just stating it (ie: "My contribution here is licensed under the same license as the project")

Thanks in advance :)

**Comment by trishnaguha** [comment]
Yes I have an account in FAS and I have signed the FPCA. My Account name is trishnag . My full name is Trishna Guha.
Thanks @pypingou

**Comment by pypingou** [comment]
Perfect, thanks @trishnaguha :)

**Comment by ralphbean** [comment]
Looks good.  Thanks all!

**Comment by trishnaguha** [comment]
Thanks @ralphbean :)

**Pull request merged**
