### PR TITLE
Release 1.0.0

### PR DESCRIPTION
**Pull request by cverna**

### CODE REVIEW

**Comment by pypingou** [comment]
We still have applications relying on flask-fas... :(

**Comment by pypingou** [comment]
In production, so this is going to break apps when the RPM reaches these hosts (or when they are re-built in openshift)

**Comment by cverna** [comment]
Do you know which applications ? we can pin the version of python-fedora ? also I am not really sure what is the future of flask-fas with securitas.

**Comment by pypingou** [comment]
pagure.io and src.fp.o are still using it for open-id.
I think fedocal and nuancier may have been (or are being) ported to oidc in git, but I don't think they were deployed.

For the future, I know we want to drop it in favor of the classic flask-openid or (preferably) OIDC but I don't think we're quite ready for this yet.
IIUC it should work with securitas as ipsilon will be configured to use its ldap backend, but applications interacts with the front-end protocols, so, in theory, shouldn't make a difference.

**Comment by pypingou** [comment]
Upon further investigation with @cverna we found that we in fact drop flask_fas back in 2016! in commit: https://github.com/fedora-infra/python-fedora/commit/0b0af2047eb2cb1156c593c1951bd6eb5fe95629
What we did here was removing the corresponding doc.

The flask plugin we are (still) using is: flask_fas_openid and this one is still shipped, so we're good :)

**Pull request merged**
